import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Planeta Vivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
